# constants.py

#
# MobileNetV3 Constants
#
MODEL_NAME_MNV3 = "mobilenetv3"
EXPERIMENT_NAME_MNV3 = "mobilenetv3-experiment-1"
EPOCHS_MNV3 = 5
BATCH_SIZE_MNV3 = 256
IMAGE_SIZE_MNV3 = 224
NUM_WORKERS_MNV3 = 2
LR_MNV3 = 1e-4
PRETRAINED_MNV3 = True
FREEZE_MNV3 = True

#
# VGG16 Constants
#
MODEL_NAME_VGG16 = "vgg16"
EXPERIMENT_NAME_VGG16 = "vgg16-experiment-8"
EPOCHS_VGG16 = 10
BATCH_SIZE_VGG16 = 128
IMAGE_SIZE_VGG16 = 224
NUM_WORKERS_VGG16 = 2
WEIGHT_DECAY_VGG16 = 0.01
LR_VGG16 = 1e-4
PRETRAINED_VGG16 = True
FREEZE_VGG16 = False
UNFREEZE_CONV_BLOCKS = 3

#
# EfficientNet-B0 Constants
#
MODEL_NAME_EFFICIENTNET_B0 = "efficientnet_b0"
EXPERIMENT_NAME_EFFICIENTNET_B0 = "efficientnetb0-experiment-test"
EPOCHS_EFFICIENTNET_B0 = 10
BATCH_SIZE_EFFICIENTNET_B0 = 64
IMAGE_SIZE_EFFICIENTNET_B0 = 224
NUM_WORKERS_EFFICIENTNET_B0 = 4
LR_EFFICIENTNET_B0 = 5e-4
WEIGHT_DECAY_EFFICIENTNET_B0 = 0.01
PRETRAINED_EFFICIENTNET_B0 = True
FREEZE_EFFICIENTNET_B0 = False


#
# ViT Constants
#
MODEL_NAME_VIT = "deit_base_patch16_224"
EPOCHS_VIT = 30
BATCH_SIZE_VIT = 128
IMAGE_SIZE_VIT = 224
NUM_WORKERS_VIT = 4
LR_VIT = 3e-5
PRETRAINED_VIT = True

#
# Shared Constants (Data Paths, etc.)
#
DATA_DIR = "data/"
SAVE_DIR = "results"
